language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jcurt11n/docker-react -f Dockerfile.dev .

# script:
#   - docker run jcurt11n/docker-react npm run test -- --coverage

script:
  - docker run -e CI=true jcurt11n/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-561110028112"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  # access_key_id: $AWS_ACCESS_KEY
  # secret_access_key:
  #   secure: "$AWS_SECRET_KEY"

